# Base-Services and network
services:

  mailhog:
    # Web Interface: http://localhost:1080/#
    # Web API: http://localhost:1080/api/v2/messages
    image: mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    logging:
      driver: none
    ports:
      - "1080:8025"
      - "1025:1025"
    networks:
      - authz-playground-net

  example-postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - default
    ports:
      - "5499:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - authz-playground-net
    volumes:
      - ./run/postgres/data:/var/lib/postgresql/data:z

networks:
  authz-playground-net:
    name: authz-playground-net